#!/usr/bin/env bash
set -e

# Copy the directory from the Nix store to a temporary location
temp_dir=$MOVEMENT_BASE_STORAGE_PATH/monza-aptos

# Change to the temporary directory
cd "$temp_dir"

# Split the listen addresses into an array
IFS=':' read -r -a listener_array <<< "$SUZUKA_APTOS_FAUCET_LISTEN_ADDR"

# Extract the listen address and port
LISTEN_ADDR="${listener_array[0]}"
LISTEN_PORT="${listener_array[1]}"

echo "Starting faucet service with the following configuration:"
echo "  - Chain ID: $SUZUKA_CHAIN_ID"
echo "  - Node URL: $SUZUKA_APTOS_REST_LISTEN_ADDR"
echo "  - Faucet URL: $SUZUKA_APTOS_FAUCET_LISTEN_ADDR"

# Run the faucet service using cargo
echo "Starting faucet service..."
./target/$CARGO_PROFILE/aptos-faucet-service run-simple --key "$MONZA_APTOS_PRIVATE_KEY" \
    --node-url "http://$MONZA_APTOS_REST_LISTEN_ADDR" --chain-id "$MONZA_CHAIN_ID" \
    --listen-address "$LISTEN_ADDR" --listen-port "$LISTEN_PORT"

# The script automatically calls cleanup when it exits due to the trap
