#!/bin/bash -e
# Change directory to the one specified in the environment variable
cd "$MONZA_APTOS_PATH" # this should be provided by nix

# Split the listen addresses into an array
IFS=':' read -r -a listener_array <<< "$MONZA_APTOS_FAUCET_LISTEN_ADDR"

# Extract the listen address and port
LISTEN_ADDR="${listener_array[0]}"
LISTEN_PORT="${listener_array[1]}"

# Run the faucet service using cargo
cargo run -p aptos-faucet-service -- run-simple --key "$MONZA_PRIVATE_KEY" \
    --node-url "http://$MONZA_APTOS_REST_LISTEN_ADDR" --chain-id "$MONZA_CHAIN_ID"