query getBridgeTransfersByInitiatorAndRecipient($initiator_address: String!, $recipient_address: String!) {
      lock_bridge_transfers(
        where: {
          initiator: { _eq: $initiator_address },
          recipient: { _eq: $recipient_address }
        }
      ) {
        bridge_transfer_id
        initiator
        recipient
        hash_lock
        amount
        state
      }
    
      initiated_events(
        where: {
          initiator_address: { _eq: $initiator_address },
          recipient_address: { _eq: $recipient_address }
        }
      ) {
        bridge_transfer_id
        initiator_address
        recipient_address
        hash_lock
        time_lock
        amount
        state
      }
    
      locked_events(
        where: {
          initiator: { _eq: $initiator_address },
          recipient: { _eq: $recipient_address }
        }
      ) {
        bridge_transfer_id
        initiator
        recipient
        hash_lock
        time_lock
        amount
        state
      }
    }