#!/bin/bash -e
export MOVE_ROCKS_CHAIN_ID="$(openssl rand -hex 10)"
export MOVE_ROCKS_PATH="$MOVEMENT_BASE_STORAGE_PATH/move-rocks/${MOVE_ROCKS_CHAIN_ID}/.move-rocks"
. ./scripts/celestia/celestia-env

# build suzuka
echo "Building suzuka-config..."
cargo build --bin suzuka-config
echo "Built suzuka-config!"

echo "Building m1-da-light-node..."
cargo build -p m1-da-light-node --features "sequencer"
echo "Built m1-da-light-node!"

echo "Building suzuka-full-node..."
cargo build -p suzuka-full-node
echo "Built suzuka-full-node!"

# build aptos
WORKING_DIR=$(pwd)
temp_dir=$MOVEMENT_BASE_STORAGE_PATH/suzuka-aptos
cp -R "$MONZA_APTOS_PATH" "$temp_dir"
chmod -R 755 $temp_dir
cd $MOVEMENT_BASE_STORAGE_PATH/suzuka-aptos
echo "Building aptos-faucet-service..."
cargo build -p aptos-faucet-service
echo "Built aptos-faucet-service!"
cd $WORKING_DIR

eval $(./target/debug/suzuka-config)
