#!/bin/bash

# Check if the correct number of arguments are passed
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <Dockerfile> <repository> <image-name>"
    exit 1
fi

# Get the current commit hash
COMMIT_HASH=$(git rev-parse HEAD)

# Get the current branch name and replace any '/' with '.'
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
SANITIZED_BRANCH_NAME=${BRANCH_NAME//\//.}

# Tag and build the Docker image
echo "Building docker image with tags $2/$3:$COMMIT_HASH and $2/$3:$SANITIZED_BRANCH_NAME"
docker build -f $1 -t $2/$3:$COMMIT_HASH -t $2/$3:$SANITIZED_BRANCH_NAME .

# Push the Docker images
docker push $2/$3:$COMMIT_HASH
docker push $2/$3:$SANITIZED_BRANCH_NAME