#!/usr/bin/env bash
set -e

: ${MOVEMENT_PREBUILT:=false}
export MOVEMENT_PREBUILT
: ${CARGO_PROFILE:=debug}
export CARGO_PROFILE

if [ "$CARGO_PROFILE" = "release" ]; then
    CARGO_PROFILE_FLAGS="--release"
else
    CARGO_PROFILE_FLAGS=""
fi

echo "Building mcr-settlement-runner..."
cargo build $CARGO_PROFILE_FLAGS -p mcr-settlement-runner
echo "Built mcr-settlement-runner!"