#!/usr/bin/env bash

sleep 10
result=$(PGPASSWORD=password psql -h $POSTGRES_HOST_IP -U postgres -d postgres -t -c "SELECT COUNT(*) FROM public.transactions;")
result=$(echo $result | xargs)
if (( result >= 1 )); then
  http_status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8085/console")
  if [ "$http_status" -eq 200 ]; then
    echo "Indexer test OK."
    exit 0
  else
      echo "Indexer test Failed."
      exit 1
  fi
else
  echo "Indexer test Failed, db not populated."
  exit 1
fi
