#!/usr/bin/env bash
export MCR_CONTRACT_DIR="$(pwd)/protocol-units/settlement/mcr/contracts"
export MCR_ANVIL_PORT=8545
export MCR_CHAIN_ID="$(shuf -i 1-32768 -n 1)"

#set the MCR_ANVIL_APP_PATH absolute if MOVEMENT_BASE_STORAGE_PATH is relatif.
CURRENT_PATH=$(pwd)
export MCR_ANVIL_APP_PATH="$CURRENT_PATH/$MOVEMENT_BASE_STORAGE_PATH/anvil/mcr/$MCR_CHAIN_ID"
mkdir -p $MCR_ANVIL_APP_PATH

# Define the path to the anvil.json file
export ANVIL_JSON_PATH="$MCR_ANVIL_APP_PATH/anvil.json"
export MCR_SC_ADDRESS_FILE="$MCR_ANVIL_APP_PATH/mcr_adress.txt"
