#!/usr/bin/env bash
export MCR_CONTRACT_DIR="$(pwd)/protocol-units/settlement/mcr/contracts"
export MCR_ANVIL_PORT=8545
export MCR_CHAIN_ID="$(shuf -i 1-32768 -n 1)"
export MCR_ANVIL_APP_PATH="$MOVEMENT_BASE_STORAGE_PATH/anvil/mcr/$MCR_CHAIN_ID"
mkdir -p $MCR_ANVIL_APP_PATH