#!/bin/bash -e
export MOVE_ROCKS_CHAIN_ID="$(openssl rand -hex 10)"
export MOVE_ROCKS_PATH="./.etc/move-rocks/${MOVE_ROCKS_CHAIN_ID}/.move-rocks"
. ./scripts/celestia/celestia-env

# build monza
cargo build --bin monza-config
cargo build -p m1-da-light-node --features "sequencer"
cargo build -p monza-full-node

# build aptos
WORKING_DIR=$(pwd)
cd ./.movement/monza-aptos
cargo build -p aptos-faucet-service
cd $WORKING_DIR

eval $(./target/debug/monza-config)