#!/usr/bin/env bash
set -e

WORKING_DIR=$(pwd)
temp_dir=$DOT_MOVEMENT/monza-aptos
cp -R "$MONZA_APTOS_PATH" "$temp_dir"
chmod -R 755 $temp_dir
cd $DOT_MOVEMENT/monza-aptos
echo "Building aptos-faucet-service..."
cargo build $CARGO_PROFILE_FLAGS -p aptos-faucet-service
echo "Built aptos-faucet-service!"
cd $WORKING_DIR