#!/usr/bin/env bash
set -e

set -a  # Automatically export all variables
source $DOT_MOVEMENT/env/celestia/.env
source $DOT_MOVEMENT/env/move/.env
source $DOT_MOVEMENT/env/monza/.env
set +a  # Disable automatic export

cargo test -p monza-client -- --test-threads=1