#!/usr/bin/env bash
set -e

set -a  # Automatically export all variables
source $DOT_MOVEMENT/env/celestia/.env
source $DOT_MOVEMENT/env/move/.env
set +a

export MONZA_ENV_STORAGE_PATH="$DOT_MOVEMENT/env/monza"
mkdir -p "$MONZA_ENV_STORAGE_PATH"

eval $(./target/$CARGO_PROFILE/monza-config)

env | grep MONZA_ > "$MONZA_ENV_STORAGE_PATH/.env"