#!/usr/bin/env bash
set -e

source $DOT_MOVEMENT/env/celestia/.env

LOG_LEVEL=$(echo "$CELESTIA_LOG_LEVEL" | awk '{print tolower($0)}')
celestia-appd start --grpc.enable --home $CELESTIA_APP_PATH --log_level $LOG_LEVEL