#!/usr/bin/env bash
set -e
set -a  # Automatically export all variables
source $DOT_MOVEMENT/env/celestia/.env
set +a  # Disable automatic export

GENESIS=
CNT=0
MAX=30

# \leq 4 because null is 4 characters long, otherwise the genesis block hash is 64 characters long
while [ "${#GENESIS}" -le 4 ] && [ $CNT -lt $MAX ]; do
    # FIXME(nix-ci-fix): if nix environment is set up incorrectly, we will get something similar to: https://github.com/commercialhaskell/stack/issues/6331
    echo "Waiting for genesis block..."
    GENESIS=$(curl -s http://127.0.0.1:26657/block?height=1 | jq '.result.block_id.hash' | tr -d '"')
    echo "Genesis: $GENESIS"
    CNT=$((CNT+1))
    sleep 1
    echo "Attempt $CNT"
done
echo "Discovered genesis: $GENESIS"

if [ "${#GENESIS}" -le 4 ]; then
    echo "Failed to retrieve genesis block after $MAX attempts."
    exit 1
fi

export CELESTIA_CUSTOM=$CELESTIA_CHAIN_ID:$GENESIS
echo "$CELESTIA_CUSTOM"

celestia bridge init --node.store $CELESTIA_NODE_PATH
celestia bridge start \
  --node.store $CELESTIA_NODE_PATH --gateway \
  --core.ip 0.0.0.0 \
  --keyring.accname validator \
  --gateway.addr 0.0.0.0 \
  --rpc.addr 0.0.0.0 \
  --log.level $CELESTIA_LOG_LEVEL