#!/usr/bin/env bash
set -e

echo "Building Bridge..."
cargo build $CARGO_PROFILE_FLAGS -p bridge-service
echo "Built Bridge!"

echo "Building Bridge..."
cargo build $CARGO_PROFILE_FLAGS -p bridge-setup
echo "Built Bridge!"
