#!/usr/bin/env bash
set -e
export MOVE_ROCKS_CHAIN_ID="$(openssl rand -hex 10)"
export MOVE_ROCKS_PATH="$MOVEMENT_BASE_STORAGE_PATH/move-rocks/${MOVE_ROCKS_CHAIN_ID}/.move-rocks"
. ./scripts/celestia/celestia-env

echo "Building m1-da-light-node..."
cargo build -p m1-da-light-node
echo "Built m1-da-light-node!"