#!/usr/bin/env bash
set -e

echo "Building m1-da-light-node..."
cargo build $CARGO_PROFILE_FLAGS -p m1-da-light-node --features "sequencer"
echo "Built m1-da-light-node!"

echo "Building m1-da-light-node-celestia-* runners..."
cargo build $CARGO_PROFILE_FLAGS -p m1-da-light-node-runners \
    --bin m1-da-light-node-celestia-appd \
    --bin m1-da-light-node-celestia-bridge
echo "Built m1-da-light-node-celestia-* runners!"

echo "Building movement-full-node..."
cargo build $CARGO_PROFILE_FLAGS -p movement-full-node
echo "Built movement-full-node!"

echo "Building movement-faucet-service..."
cargo build $CARGO_PROFILE_FLAGS -p movement-faucet-service
echo "Built movement-faucet-service!"

echo "Building movement-full-node-setup..."
cargo build $CARGO_PROFILE_FLAGS -p movement-full-node-setup
echo "Built movement-full-node-setup!"

echo "Building wait-for-celestia-light-node..."
cargo build $CARGO_PROFILE_FLAGS -p m1-da-light-node-util --bin wait-for-celestia-light-node
echo "Built wait-for-celestia-light-node!"

echo "Building Bridge..."
cargo build $CARGO_PROFILE_FLAGS -p bridge-service
echo "Built Bridge!"

echo "Building Bridge..."
cargo build $CARGO_PROFILE_FLAGS -p bridge-setup
echo "Built Bridge!"