#!/usr/bin/env bash
set -e

: ${MOVEMENT_PREBUILT:=false}
export MOVEMENT_PREBUILT
: ${CARGO_PROFILE:=debug}
export CARGO_PROFILE

if [ "$CARGO_PROFILE" = "release" ]; then
    CARGO_PROFILE_FLAGS="--release"
else
    CARGO_PROFILE_FLAGS=""
fi

echo "Building movement-celestia-da-light-node..."
cargo build $CARGO_PROFILE_FLAGS -p movement-celestia-da-light-node --features "sequencer"
echo "Built movement-celestia-da-light-node!"

echo "Building movement-celestia-da-light-node-runners..."
cargo build $CARGO_PROFILE_FLAGS -p movement-celestia-da-light-node-runners
echo "Built movement-celestia-da-light-node-runners!"
