#!/usr/bin/env bash
set -e
set -euo pipefail

IFS='.' read -r -a split <<< "$3"

override_files=()
for element in "${split[@]}"; do
    override_files+=("-f")
    override_files+=("docker/compose/$1/docker-compose.$element.yml")
done

echo "Running process-compose for $1 with override files: ${override_files[@]}..."
docker compose --env-file .env -f docker/compose/$1/docker-compose.yml "${override_files[@]}"  "${@:4}" up 