#!/usr/bin/env bash
set -e
set -euo pipefail

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <service> <runtime> <flags> [docker-compose flags...]"
    echo "Example: $0 suzuka-full-node native setup.local.test"
    exit 1
fi

SERVICE=$1
RUNTIME=$2
FLAGS=$3

IFS='.' read -r -a split <<< "$FLAGS"

override_files=()
for element in "${split[@]}"; do
    override_files+=("-f")
    override_files+=("docker/compose/$SERVICE/docker-compose.$element.yml")
done

echo "Running docker-compose for $SERVICE with override files: ${override_files[@]}..."
docker compose --env-file .env -f docker/compose/$SERVICE/docker-compose.yml "${override_files[@]}" up "${@:4}"