#!/usr/bin/env bash
set -e
set -x
set -euo pipefail

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <service> <runtime> <flags> [process-compose flags...]"
    echo "Example: $0 movement-full-node native setup.local.test"
    exit 1
fi

SERVICE=$1
RUNTIME=$2 # runtime is already known, but we reuse
FEATURES=$3

IFS='.' read -r -a split <<< "$FEATURES"

override_files=()
for element in "${split[@]}"; do
    override_files+=("-f")
    override_files+=("process-compose/$SERVICE/process-compose.$element.yml")
done

echo "Running process-compose for $SERVICE with override files: ${override_files[@]}..."
process-compose -f process-compose/$SERVICE/process-compose.yml "${override_files[@]}" "${@:4}"
