#!/usr/bin/env bash
set -euo pipefail

export PATH=$PATH:./target/release

MOVEMENT_BASE_STORAGE_PATH=$(mktemp -d -t m2-XXXXXXXX)
export MOVEMENT_BASE_STORAGE_PATH
echo "Using sequencer storage path: $MOVEMENT_BASE_STORAGE_PATH"

. ./scripts/celestia-env

# If keeping the storage path, is desired for debugging, comment out the line
# below or set a custom storage path in process-compose.yaml.
trap "exit" INT TERM
trap cleanup EXIT
cleanup(){
    echo "Cleaning up storage: $MOVEMENT_BASE_STORAGE_PATH"
    rm -rv "$MOVEMENT_BASE_STORAGE_PATH"
}

. ./scripts/preludes/$1/prelude run
process-compose "${@:2}" -f process-compose/$1/run/process-compose.yml