#!/usr/bin/env bash
set -e

if [ "$CARGO_PROFILE" = "release" ]; then
    CARGO_PROFILE_FLAGS="--release"
else
    CARGO_PROFILE_FLAGS=""
fi

#echo "Building movement-celestia-da-light-node..."
#cargo build $CARGO_PROFILE_FLAGS -p movement-celestia-da-light-node --features "sequencer"
#echo "Built movement-celestia-da-light-node!"

echo "Building movement-celestia-* runners..."
cargo build $CARGO_PROFILE_FLAGS -p movement-celestia-da-light-node-runners
echo "Built movement-celestia-* runners!"

echo "Building movement-full-node..."
cargo build $CARGO_PROFILE_FLAGS -p movement-full-node
echo "Built movement-full-node!"

echo "Building movement-faucet-service..."
cargo build $CARGO_PROFILE_FLAGS -p movement-faucet-service
echo "Built movement-faucet-service!"

echo "Building da-sequencer-node..."
cargo build $CARGO_PROFILE_FLAGS -p movement-da-sequencer-node
echo "Built da-sequencer-node"

