#!/usr/bin/env bash
set -e

echo "Building movement-full-node..."
cargo build $CARGO_PROFILE_FLAGS -p movement-full-node
echo "Built movement-full-node!"

echo "Building movement-faucet-service..."
cargo build $CARGO_PROFILE_FLAGS -p movement-faucet-service
echo "Built movement-faucet-service!"

echo "Building movement-full-node-setup..."
cargo build $CARGO_PROFILE_FLAGS -p movement-full-node-setup
echo "Built movement-full-node-setup!"

echo "Bulding movement-util..."
cargo build $CARGO_PROFILE_FLAGS -p movement-util
echo "Built movement-util!"
