#!/usr/bin/env bash
set -e

: ${MOVEMENT_PREBUILT:=false}
export MOVEMENT_PREBUILT
: ${CARGO_PROFILE:=debug}
export CARGO_PROFILE

if [ "$CARGO_PROFILE" = "release" ]; then
    CARGO_PROFILE_FLAGS="--release"
else
    CARGO_PROFILE_FLAGS=""
fi

echo "Building wait-for-celestia-light-node..."
cargo build $CARGO_PROFILE_FLAGS -p m1-da-light-node-util --bin wait-for-celestia-light-node
echo "Built wait-for-celestia-light-node!"
