#!/bin/bash -e
# Copy the snapshot

export AWS_REGION="us-west-1";

echo "Starting node for 60 seconds..."
# Run the node for 60 seconds, terminating if it exceeds the time limit
if timeout 60s movement-full-node run; then
    echo "Node run completed within the time limit."
else
    echo "Node run did not complete within the time limit. Forcefully terminated."
fi
echo "Taking snapshot..."
if movement-full-node backup save-and-push; then
    echo "Snapshot taken successfully."
else
    echo "Snapshot process failed. Exiting loop."
    break
fi

echo "Remove node DB"
rm -rf "${DOT_MOVEMENT_PATH}/maptos*";
rm -rf "${DOT_MOVEMENT_PATH}/movement-da-db";

echo "Restore snapshot..."
export RUST_BACKTRACE=1;
if movement-full-node backup restore; then
    echo "Snapshot restored successfully."
else
    echo "Snapshot restoration failed. Exiting loop."
    break
fi

export MAYBE_RUN_LOCAL=true;

echo "Starting new node with the backup db for 60 seconds..."
if timeout 60s movement-full-node run; then
    echo "Node run completed within the time limit."
else
    echo "Node run did not complete within the time limit. Forcefully terminated."
fi



done