#!/usr/bin/env bash
set -e

echo "Building suzuka-config..."
cargo build $CARGO_PROFILE_FLAGS --bin suzuka-full-node-setup
echo "Built suzuka-config!"

echo "Building suzuka-full-node..."
cargo build $CARGO_PROFILE_FLAGS -p suzuka-full-node
echo "Built suzuka-full-node!"