#!/usr/bin/env bash
set -e
export MOVE_ENV_STORAGE_PATH="$DOT_MOVEMENT/env/celestia"
export MOVE_ROCKS_CHAIN_ID="$(openssl rand -hex 10)"
export MOVE_ROCKS_PATH="$DOT_MOVEMENT/move-rocks/${MOVE_ROCKS_CHAIN_ID}/.move-rocks"

env | grep MOVE_ > "$MOVE_ENV_STORAGE_PATH/.env"