#!/bin/bash -e
APP_PATH="./.etc/celestia/${CELESTIA_CHAIN_ID}/.celestia-app"
NODE_PATH="./.etc/celestia/${CELESTIA_CHAIN_ID}/bridge"

GENESIS=
CNT=0
MAX=30
while [ "${#GENESIS}" -le 4 -a $CNT -ne $MAX ]; do
	GENESIS=$(curl -s http://127.0.0.1:26657/block?height=1 | jq '.result.block_id.hash' | tr -d '"')
	((CNT++))
	sleep 1
done

export CELESTIA_CUSTOM=$CELESTIA_CHAIN_ID:$GENESIS
echo "$CELESTIA_CUSTOM"

celestia bridge init --node.store $NODE_PATH
celestia bridge start \
  --node.store $NODE_PATH --gateway \
  --core.ip 127.0.0.1 \
  --keyring.accname validator \
  --gateway.addr 0.0.0.0 \
  --rpc.addr 0.0.0.0 \