#!/bin/bash -e
APP_PATH="./.etc/celestia/${CELESTIA_CHAIN_ID}/.celestia-app"
NODE_PATH="./.etc/celestia/${CELESTIA_CHAIN_ID}/bridge"

# Check if the folder exists
if [ -d "$APP_PATH" ]; then
  # If it exists, delete it
  echo "The folder $APP_PATH exists. Deleting it..."
  rm -rf "$APP_PATH"
  echo "Folder deleted."
else
  # If it doesn't exist, print a message
  echo "The folder $APP_PATH does not exist."
fi

# Build genesis file incl account for passed address
coins="1000000000000000utia"
celestia-appd init $CELESTIA_CHAIN_ID --chain-id $CELESTIA_CHAIN_ID --home $APP_PATH
celestia-appd keys add validator --keyring-backend="test" --home $APP_PATH
# this won't work because some proto types are declared twice and the logs output to stdout (dependency hell involving iavl)
celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend="test" --home $APP_PATH) $coins --home $APP_PATH
celestia-appd gentx validator 5000000000utia \
  --keyring-backend="test" \
  --chain-id $CELESTIA_CHAIN_ID \
  --home $APP_PATH \

celestia-appd collect-gentxs --home $APP_PATH

# Set proper defaults and change ports
# If you encounter: `sed: -I or -i may not be used with stdin` on MacOS you can mitigate by installing gnu-sed
# https://gist.github.com/andre3k1/e3a1a7133fded5de5a9ee99c87c6fa0d?permalink_comment_id=3082272#gistcomment-3082272
sed -i'.bak' 's#"tcp://127.0.0.1:26657"#"tcp://0.0.0.0:26657"#g' $APP_PATH/config/config.toml
sed -i'.bak' 's/^timeout_commit\s*=.*/timeout_commit = "2s"/g' $APP_PATH/config/config.toml
sed -i'.bak' 's/^timeout_propose\s*=.*/timeout_propose = "2s"/g' $APP_PATH/config/config.toml

mkdir -p $NODE_PATH/keys
cp -r $APP_PATH/keyring-test/ $NODE_PATH/keys/keyring-test/