#!/usr/bin/env bash
set -e
# Maximum number of retries
max_retries=10
# Delay in seconds between retries
retry_delay=5

retry_count=0
success=false

while [ $retry_count -lt $max_retries ]; do
    # Run the curl command
    response=$(curl -s -X POST 'https://faucet.celestia-arabica-11.com/api/v1/faucet/give_me' \
        -H 'Content-Type: application/json' \
        -d "{\"address\": \"$CELESTIA_ADDRESS\", \"chainId\": \"arabica-11\"}")
    
    # Process the response with jq
    txHash=$(echo "$response" | jq -e '.txHash')
    
    # Check if jq found the txHash
    if [ $? -eq 0 ]; then
        echo "Transaction hash: $txHash"
        success=true
        break
    else
        echo "Error: txHash field not found in the response." >&2
        # Increment the retry counter
        retry_count=$((retry_count+1))
        # Wait before retrying
        sleep $retry_delay
    fi
done

# Check if the operation was successful
if [ "$success" = false ]; then
    echo "Failed to retrieve txHash after $max_retries attempts." >&2
fi
